kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-efs
  namespace: roboshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 4Gi